# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'l3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 383)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tev = QtWidgets.QTextEdit(self.centralwidget)
        self.tev.setGeometry(QtCore.QRect(10, 20, 481, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tev.setFont(font)
        self.tev.setObjectName("tev")
        self.tep = QtWidgets.QTextEdit(self.centralwidget)
        self.tep.setGeometry(QtCore.QRect(520, 20, 481, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tep.setFont(font)
        self.tep.setObjectName("tep")
        self.vf = QtWidgets.QPushButton(self.centralwidget)
        self.vf.setGeometry(QtCore.QRect(10, 290, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vf.setFont(font)
        self.vf.setObjectName("vf")
        self.zh = QtWidgets.QPushButton(self.centralwidget)
        self.zh.setGeometry(QtCore.QRect(220, 290, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zh.setFont(font)
        self.zh.setObjectName("zh")
        self.dh = QtWidgets.QPushButton(self.centralwidget)
        self.dh.setGeometry(QtCore.QRect(490, 290, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dh.setFont(font)
        self.dh.setObjectName("dh")
        self.lz78 = QtWidgets.QPushButton(self.centralwidget)
        self.lz78.setGeometry(QtCore.QRect(760, 290, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lz78.setFont(font)
        self.lz78.setObjectName("lz78")
        self.lzw = QtWidgets.QPushButton(self.centralwidget)
        self.lzw.setGeometry(QtCore.QRect(890, 290, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lzw.setFont(font)
        self.lzw.setObjectName("lzw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.vf.setText(_translate("MainWindow", "Выбрать файл"))
        self.zh.setText(_translate("MainWindow", "Закодировать Хаффман"))
        self.dh.setText(_translate("MainWindow", "Декодировать Хаффман"))
        self.lz78.setText(_translate("MainWindow", "LZ78"))
        self.lzw.setText(_translate("MainWindow", "LZW"))
